/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author rajar
 */
public class BulkMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public BulkMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        txtStatus = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 600));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setSize(new java.awt.Dimension(500, 600));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BULK PHISHING DETECTOR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 50));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMaximumSize(new java.awt.Dimension(400, 180));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(400, 180));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 180));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new java.awt.GridBagConstraints());

        jButton1.setText("Check");
        jButton1.setMaximumSize(new java.awt.Dimension(75, 180));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 180));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 180));
        jPanel1.add(jButton1, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 350));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 350));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane3.setMaximumSize(new java.awt.Dimension(475, 300));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(475, 300));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(475, 300));

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Url", "Point", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.setMaximumSize(new java.awt.Dimension(475, 300));
        tblList.setMinimumSize(new java.awt.Dimension(475, 300));
        tblList.setPreferredSize(new java.awt.Dimension(475, 300));
        jScrollPane3.setViewportView(tblList);
        if (tblList.getColumnModel().getColumnCount() > 0) {
            tblList.getColumnModel().getColumn(0).setMinWidth(25);
            tblList.getColumnModel().getColumn(0).setPreferredWidth(25);
            tblList.getColumnModel().getColumn(0).setMaxWidth(25);
            tblList.getColumnModel().getColumn(2).setMinWidth(50);
            tblList.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblList.getColumnModel().getColumn(2).setMaxWidth(50);
            tblList.getColumnModel().getColumn(3).setMinWidth(125);
            tblList.getColumnModel().getColumn(3).setPreferredWidth(125);
            tblList.getColumnModel().getColumn(3).setMaxWidth(125);
        }

        jPanel2.add(jScrollPane3, new java.awt.GridBagConstraints());

        txtStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStatus.setText("Status: Ready to Check");
        txtStatus.setMaximumSize(new java.awt.Dimension(500, 15));
        txtStatus.setMinimumSize(new java.awt.Dimension(500, 15));
        txtStatus.setPreferredSize(new java.awt.Dimension(500, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel2.add(txtStatus, gridBagConstraints);

        jButton2.setText("Individual Detecting");
        jButton2.setMaximumSize(new java.awt.Dimension(500, 35));
        jButton2.setMinimumSize(new java.awt.Dimension(500, 35));
        jButton2.setPreferredSize(new java.awt.Dimension(500, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel2.add(jButton2, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BulkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BulkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BulkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BulkMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BulkMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tblList;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables

    public JTextArea getField(){
        return jTextArea2;
    }
    
    public JButton getButton(){
        return jButton1;
    }
    
    public JButton getBulk(){
        return jButton2;
    }

    public JTable getTblList() {
        return tblList;
    }

    public void setTblList(JTable tblList) {
        this.tblList = tblList;
    }

    public JLabel getTxtStatus() {
        return txtStatus;
    }
    
}
