/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author rajar
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 600));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setSize(new java.awt.Dimension(500, 600));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHISHING DETECTOR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 50));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 25));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 25));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField2.setMaximumSize(new java.awt.Dimension(400, 35));
        jTextField2.setMinimumSize(new java.awt.Dimension(400, 35));
        jTextField2.setPreferredSize(new java.awt.Dimension(400, 35));
        jPanel1.add(jTextField2, new java.awt.GridBagConstraints());

        jButton1.setText("Check");
        jButton1.setMaximumSize(new java.awt.Dimension(75, 35));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 35));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 35));
        jPanel1.add(jButton1, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 475));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 475));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 475));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(475, 440));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(475, 440));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(475, 440));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextArea1.setMaximumSize(new java.awt.Dimension(465, 55));
        jTextArea1.setMinimumSize(new java.awt.Dimension(465, 55));
        jTextArea1.setPreferredSize(new java.awt.Dimension(465, 55));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new java.awt.GridBagConstraints());

        jButton2.setText("Bulk Detecting");
        jButton2.setMaximumSize(new java.awt.Dimension(500, 35));
        jButton2.setMinimumSize(new java.awt.Dimension(500, 35));
        jButton2.setPreferredSize(new java.awt.Dimension(500, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel2.add(jButton2, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public JTextField getTextField(){
        return jTextField2;
    }
    
    public JTextArea getTextArea(){
        return jTextArea1;
    }
    
    public JButton getButton(){
        return jButton1;
    }
    
    public JButton getBulk(){
        return jButton2;
    }
}
